name: Test

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install --ignore-scripts
      - name: Test
        run: npm run test:coverage
      - name: Build
        run: npm run build -- --prod
      - name: Codecov
        run: ./node_modules/.bin/codecov --token=${{ secrets.CODECOV_TOKEN }}

  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install --ignore-scripts
      - name: Pre Test
        run: npx webdriver-manager update --versions.chrome=80.0.3987.106
      - name: Test
        run: npm run test:e2e -- --prod --webdriver-update false
